// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
<<<<<<<< Updated upstream:Backend/Migrations/UserDb/20250424182420_InitialCreateForUserNew.Designer.cs
    [Migration("20250424182420_InitialCreateForUserNew")]
    partial class InitialCreateForUserNew
========
    [Migration("20250507015053_AddUrlImagesToUsersNewUpdate")]
    partial class AddUrlImagesToUsersNewUpdate
>>>>>>>> Stashed changes:Backend/Migrations/UserDb/20250507015053_AddUrlImagesToUsersNewUpdate.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.UserNew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< Updated upstream:Backend/Migrations/UserDb/20250424182420_InitialCreateForUserNew.Designer.cs
========
                    b.Property<string>("UrlImages")
                        .HasColumnType("nvarchar(max)");

>>>>>>>> Stashed changes:Backend/Migrations/UserDb/20250507015053_AddUrlImagesToUsersNewUpdate.Designer.cs
                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersNew");
                });
#pragma warning restore 612, 618
        }
    }
}
